Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('pwa.urls')),
]

admin.site.site_title = "FlorArte"
admin.site.site_header = "Administración de la Florería"
admin.site.index_title = "Módulos de la Aplicación"

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('producto', ProductoViewSet)

urlpatterns = [
    path('', index, name="index"),
    path('quienes/', quienes, name="quienes"),
    path('producto/', producto, name="producto"),
    path('suscripcion/', suscriptor, name="suscripcion"),
    path('agregar_producto/', agregar_producto, name="agregar_producto"),
    path('modificar_producto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminar_producto/<id>/', eliminar_producto, name="eliminar_producto"),
    path('registro_usuario/', registro_usuario, name="registro_usuario"),
    path('api/', include(router.urls))


]

app/models.py
from django.db import models

# Create your models here.

class TipoProducto(models.Model):
    tipo = models.CharField(max_length=40)

    def __str__(self):
        return self.tipo

class Producto(models.Model):
    nombre = models.CharField(max_length=40)
    precio = models.IntegerField()
    descripcion = models.CharField(max_length=40)
    tipo = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)
    imagen = models.ImageField(null=True, blank=True)


    def __str__(self):
        return self.nombre

opcion_pago = [
    [0,"DEBITO"],
    [1,"CREDITO"],
]

monto_donacion = [
    [0, 4990],
    [1, 5990],
    [2, 6990],
    
]

class suscriptor(models.Model):
    nombre = models.CharField(max_length=40)
    correo = models.EmailField()
    tipo_pago=models.IntegerField(choices=opcion_pago)
    monto_donacion=models.IntegerField(choices=monto_donacion)

    def __str__(self):
        return self.nombre

app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.db import models
from django.forms import ModelForm, fields
from django import forms
from django.db import models
from django.forms import ModelForm, fields
from .models import Producto, suscriptor
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .validators import TamañoMaximoValidator

class ProductoForm(ModelForm):

    nombre = forms.CharField(min_length=5, max_length=80)
    precio = forms.IntegerField(min_value= 5000)
    descripcion = forms.CharField(min_length=5, max_length=200)
    imagen = forms.ImageField(validators=[TamañoMaximoValidator(3)], required=False)

    def clean_nombre(self):
        nom = self.cleaned_data["nombre"]
        aux = Producto.objects.filter(nombre__iexact=nom).exists()

        if aux:
            raise ValidationError("Este producto ya existe")

        return nom  

    class Meta:
        model = Producto
        fields = '__all__'
        fields = ['nombre','precio','descripcion', 'tipo', 'imagen']


class UsuarioCreationForm(UserCreationForm):

    def clean_user(self):
        use = self.cleaned_data["username"]
        aux = Producto.objects.filter(nombre__iexact=use).exists()

        if aux:
            raise ValidationError("Este usuario ya existe")

        return use 

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

class suscriptorForm(ModelForm):

    class Meta:
        model = suscriptor
        fields = ['nombre','correo','tipo_pago','monto_donacion']

app/views.py
from django.contrib.auth import authenticate, login
from django.core import paginator
from app.forms import ProductoForm, UsuarioCreationForm, suscriptorForm
from app.models import Producto
from django.shortcuts import render, redirect 
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth.decorators import permission_required
from rest_framework import viewsets
from .serializers import ProductoSerializer
# Create your views here.

def index(request):
    productosAll = Producto.objects.all()
    datos = {
        'listasProductos' : productosAll,
    }
    return render(request, 'app/index.html', datos)
    

def producto(request):
    productosAll = Producto.objects.all()
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(productosAll, 5)
        productosAll = paginator.page(page)
    except:
        raise Http404

    datos = {
        'listasProductos' : productosAll,
        'paginator' : paginator
    }
    return render(request, 'app/producto.html', datos)

def quienes(request):
    return render(request, 'app/quienes.html')

def registro_usuario(request):
    datos = {
        'form' : UsuarioCreationForm()
    }

    if request.method == 'POST':
        formulario = UsuarioCreationForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
            login(request, user)
            return redirect(to="index")
        datos['form'] = formulario

    return render(request, 'registration/signup.html', datos)

def agregar_producto(request):
    datos = {
        'form' : ProductoForm()
    }

    if request.method == 'POST':
        formulario = ProductoForm(request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            datos['mensaje'] = "Producto guardado correctamente"

        datos['form'] = formulario

    return render(request, 'app/agregar_producto.html', datos)

def modificar_producto(request, id):
    producto = Producto.objects.get(id=id)
    datos = {
        'form' : ProductoForm(instance=producto)
    }

    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            datos['form'] = formulario

    return render(request, 'app/modificar_producto.html', datos)


def eliminar_producto(request, id):
    producto = Producto.objects.get(id=id)
    producto.delete()

    return redirect(to="producto")

class ProductoViewSet(viewsets.ModelViewSet):
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer


def suscriptor (request):
    data ={ 
        'form' : suscriptorForm()
    } 

    if request.method == 'POST':
        formulario = suscriptorForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
        else:
            data['form'] = formulario

    return render(request,'app/suscripcion.html',data)
    

app/templates/app/agregar_producto.html
{% extends 'app/base.html' %}
{% load static %}
{% load materializecss %}
{% block contenido %}

<br><br><br><br><br><br>
<div class="row">
    <div class="col l2"></div>
    <div class="col l8">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
            <br><br>
            {% if perms.app.add_producto %}
            <input type="submit" class="btn" value="Guardar">
            <input type="reset" class="btn" value="Limpiar">
            {% endif%}
            <br><br><br><br><br><br><br>
        </form>
        {{ mensaje }}
    </div>
    <div class="col l2"></div>
</div>

{% endblock %}

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Inicio</title>
    {% load static %}
    {% block css %}

    {% endblock %}
    
    {% load pwa %}

    {% progressive_web_app_meta %}

    <link rel="stylesheet" href="{% static 'app/dist/css/FlorArte.css' %}">

    <link rel="stylesheet" href="{% static 'app/dist/css/materialize.css' %}">

    <link rel="stylesheet" href="{% static 'app/dist/css/materialize.min.css' %}">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
        integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />


</head>

<body>
    <!-- Navbar -->
    {% if perms.app.view_producto or perms.app.change_producto or perms.app.delete_producto or perms.app.add_producto %}
    <ul id="dropdown1" class="dropdown-content">
        <li><a href="{% url 'agregar_producto' %}">Agregar</a></li>
        <li><a href="{% url 'producto' %}">Modificar</a></li>
        <li><a href="{% url 'producto' %}">Eliminar</a></li>
    </ul>
    {% endif %}

    {% if perms.app.view_producto or perms.app.change_producto or perms.app.delete_producto or perms.app.add_producto %}
    <ul id="dropdown2" class="dropdown-content">
        <li><a href="{% url 'agregar_producto' %}">Agregar</a></li>
        <li><a href="{% url 'producto' %}">Modificar</a></li>
        <li><a href="{% url 'producto' %}">Eliminar</a></li>
    </ul>
    {% endif %}

    {% if user.is_authenticated %}
    <ul id="dropdown3" class="dropdown-content">
        <li><a href="">{{ user.username }}</a></li>
        <li><a href="{% url 'logout' %}"> Cerrar Sesión</a></li>
    </ul>
    
    <ul id="dropdown4" class="dropdown-content">
        <li><a href="">{{ user.username }}</a></li>
        <li><a href="{% url 'logout' %}"> Cerrar Sesión</a></li>
    </ul>
    {% endif %}

    <nav>
        <div class="nav-wrapper pink lighten-3">
            <a href="{% url 'index' %}" class="brand-logo">FLORARTE</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown3">Mi Perfil<i class="material-icons right">arrow_drop_down</i></a></li>
                {% endif %}
                {% if perms.app.view_producto or perms.app.change_producto or perms.app.delete_producto or perms.app.add_producto %}
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Editar<i class="material-icons right">arrow_drop_down</i></a></li>
                {% endif %}
                <li><a href="{% url 'index' %}">Inicio</a></li>
                <li><a href="{% url 'quienes' %}">Quienes Somos</a></li>
                <li><a href="{% url 'suscripcion' %}">Suscripcion</a></li>
                {% if not user.is_authenticated %}
                <li><a href="{% url 'registro_usuario' %}">Registrar</a></li>
                {% endif %}
                {% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}" class="btn">Iniciar Sesión</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- /.navbar -->

    <ul class="sidenav pink lighten-5" id="mobile-demo">
        <li><a href="{% url 'index' %}">Inicio</a></li>
        <li><a href="{% url 'quienes' %}">Quienes Somos</a></li>
        <li><a href="{% url 'suscripcion' %}">Suscripcion</a></li>
        {% if not user.is_authenticated %}
        <li><a href="{% url 'registro_usuario' %}">Registrar</a></li>
        {% endif %}
        {% if perms.app.view_producto or perms.app.change_producto or perms.app.delete_producto or perms.app.add_producto%}
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Editar<i class="material-icons right">arrow_drop_down</i></a></li>
        {% endif %}
        {% if user.is_authenticated %}
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown4">Mi Perfil<i class="material-icons right">arrow_drop_down</i></a></li>
        {% else %}
        <li><a href="{% url 'login' %}" class="btn">Iniciar Sesión</a></li>
        {% endif %}
    </ul>

    <!-- INICIALIZACIÓN NAVBAR -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems);
        });</script>
    <!-- FIN NAVBAR -->

    <div class="container-fluid"></div>
    {% block contenido %}

    {% endblock %}
    </div>

    <!-- INICIO FOOTER -->
    <footer class="page-footer pink lighten-3" id="footer-despacho">
        <div class="container">
            <div class="row">
                <div class="col l4 m4 s6" id="contenido-footer">
                    <h5 class="white-text">Vinculos Rapidos</h5>
                    <div class="contenedor-links">
                        <ul>
                            <li><a class="grey-text text-lighten-3" href="#!">Fundación</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">FAQ</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">Reclamos</a></li>
                        </ul>
                        <p class="copyright">© 2021 Florarte. All rights reserved.</p>
                    </div>
                </div>
                <div class="col l4 m4 s6">
                    <h5 class="white-text"> Nosotros</h5>
                    <div class="contenedor-links">
                        <ul>
                            <li><a class="grey-text text-lighten-3" href="{% url 'quienes' %}">Mision y
                                    Vision</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">Trabaja con nosotros</a></li>
                        </ul>
                    </div>
                </div>
    </footer>
    <!-- FIN FOOTER -->
    {% block javascript %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
        integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

    <script src="sweetalert2.all.min.js"></script>

    <!-- jQuery -->
    <script src="{% static 'app/plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'app/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'app/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'app/plugins/chart.js/Chart.min.js' %}"></script>
    <!-- Sparkline -->
    <script src="{% static 'app/plugins/sparklines/sparkline.js' %}"></script>
    <!-- JQVMap -->
    <script src="{% static 'app/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'app/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'app/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static 'app/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'app/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'app/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Summernote -->
    <script src="{% static 'app/plugins/summernote/summernote-bs4.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'app/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'app/dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'app/dist/js/demo.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'app/dist/js/pages/dashboard.js' %}"></script>

    <script>
        $(document).ready(function () {

            // Initialize materialize data picker
            $('.datepicker').datepicker({ 'format': 'yyyy-mm-dd' });
            $('select').formSelect();

        });
    </script>

    <script src="{% static 'app/dist/js/materialize.js' %}"></script>

    <script src="{% static 'app/dist/js/materialize.min.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- INICIALIZACION MODAL -->
    <script>document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.modal');
            var instances = M.Modal.init(elems);
        });</script>

    <script>
        $(".dropdown-trigger").dropdown();
    </script>

</body>

</html>

app/templates/app/base2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Inicio</title>
    {% load static %}
    {% block css %}

    {% endblock %}

    {% load pwa %}

    {% progressive_web_app_meta %}

    <link rel="stylesheet" href="{% static 'app/dist/css/FlorArte.css' %}">

    <link rel="stylesheet" href="{% static 'app/dist/css/materialize.css' %}">

    <link rel="stylesheet" href="{% static 'app/dist/css/materialize.min.css' %}">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/css/materialize.min.css"
        integrity="sha256-qj3p6P1fJIV+Ndv7RW1ovZI2UhOuboj9GcODzcNFIN8=" crossorigin="anonymous" />


</head>

<body>
    
    <!-- Navbar -->
    {% if perms.app.view_producto or perms.app.change_producto or perms.app.delete_producto or perms.app.add_producto %}
    <ul id="dropdown1" class="dropdown-content">
        <li><a href="{% url 'agregar_producto' %}">Agregar</a></li>
        <li><a href="{% url 'producto' %}">Modificar</a></li>
        <li><a href="{% url 'producto' %}">Eliminar</a></li>
    </ul>
    {% endif %}

    {% if perms.app.view_producto or perms.app.change_producto or perms.app.delete_producto or perms.app.add_producto %}
    <ul id="dropdown2" class="dropdown-content">
        <li><a href="{% url 'agregar_producto' %}">Agregar</a></li>
        <li><a href="{% url 'producto' %}">Modificar</a></li>
        <li><a href="{% url 'producto' %}">Eliminar</a></li>
    </ul>
    {% endif %}

    {% if user.is_authenticated %}
    <ul id="dropdown3" class="dropdown-content">
        <li><a href="">{{ user.username }}</a></li>
        <li><a href="{% url 'logout' %}"> Cerrar Sesión</a></li>
    </ul>
    
    <ul id="dropdown4" class="dropdown-content">
        <li><a href="">{{ user.username }}</a></li>
        <li><a href="{% url 'logout' %}"> Cerrar Sesión</a></li>
    </ul>
    {% endif %}

    <nav>
        <div class="nav-wrapper pink lighten-3">
            <a href="{% url 'index' %}" class="brand-logo">FLORARTE</a>
            <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown3">Mi Perfil<i class="material-icons right">arrow_drop_down</i></a></li>
                {% endif %}
                {% if perms.app.view_producto or perms.app.change_producto or perms.app.delete_producto or perms.app.add_producto %}
                <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Editar<i class="material-icons right">arrow_drop_down</i></a></li>
                {% endif %}
                <li><a href="{% url 'index' %}">Inicio</a></li>
                <li><a href="{% url 'quienes' %}">Quienes Somos</a></li>
                <li><a href="{% url 'suscripcion' %}">Suscripcion</a></li>
                {% if not user.is_authenticated %}
                <li><a href="{% url 'registro_usuario' %}">Registrar</a></li>
                {% endif %}
                {% if not user.is_authenticated %}
                <li><a href="{% url 'login' %}" class="btn">Iniciar Sesión</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- /.navbar -->

    <ul class="sidenav pink lighten-5" id="mobile-demo">
        <li><a href="{% url 'index' %}">Inicio</a></li>
        <li><a href="{% url 'quienes' %}">Quienes Somos</a></li>
        <li><a href="{% url 'suscripcion' %}">Suscripcion</a></li>
        {% if not user.is_authenticated %}
        <li><a href="{% url 'registro_usuario' %}">Registrar</a></li>
        {% endif %}
        {% if perms.app.view_producto or perms.app.change_producto or perms.app.delete_producto or perms.app.add_producto%}
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Editar<i class="material-icons right">arrow_drop_down</i></a></li>
        {% endif %}
        {% if user.is_authenticated %}
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown4">Mi Perfil<i class="material-icons right">arrow_drop_down</i></a></li>
        {% else %}
        <li><a href="{% url 'login' %}" class="btn">Iniciar Sesión</a></li>
        {% endif %}
    </ul>

    <!-- INICIALIZACIÓN NAVBAR -->
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems);
        });</script>
    <!-- FIN NAVBAR -->

    <div class="container-fluid"></div>
    {% block contenidos %}

    {% endblock %}
    </div>

    <!-- INICIO FOOTER -->
    <footer class="page-footer pink lighten-3" id="footer-inicio">
        <div class="container">
            <div class="row">
                <div class="col l4 m4 s6" id="contenido-footer">
                    <h5 class="white-text">Vinculos Rapidos</h5>
                    <div class="contenedor-links">
                        <ul>
                            <li><a class="grey-text text-lighten-3" href="#!">Fundación</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">FAQ</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">Reclamos</a></li>
                        </ul>
                        <p class="copyright">© 2021 Florarte. All rights reserved.</p>
                    </div>
                </div>
                <div class="col l4 m4 s6">
                    <h5 class="white-text"> Nosotros</h5>
                    <div class="contenedor-links">
                        <ul>
                            <li><a class="grey-text text-lighten-3" href="{% url 'quienes' %}">Mision y
                                    Vision</a></li>
                            <li><a class="grey-text text-lighten-3" href="#!">Trabaja con nosotros</a></li>
                        </ul>
                    </div>
                </div>
    </footer>
    <!-- FIN FOOTER -->
    {% block javascripts %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"
        integrity="sha256-SrBfGi+Zp2LhAvy9M1bWOCXztRU9Ztztxmu5BcYPcPE=" crossorigin="anonymous"></script>

    <script src="sweetalert2.all.min.js"></script>

    <!-- jQuery -->
    <script src="{% static 'app/plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'app/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'app/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'app/plugins/chart.js/Chart.min.js' %}"></script>
    <!-- Sparkline -->
    <script src="{% static 'app/plugins/sparklines/sparkline.js' %}"></script>
    <!-- JQVMap -->
    <script src="{% static 'app/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'app/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'app/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static 'app/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'app/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'app/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Summernote -->
    <script src="{% static 'app/plugins/summernote/summernote-bs4.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'app/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'app/dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'app/dist/js/demo.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'app/dist/js/pages/dashboard.js' %}"></script>

    <script>
        $(document).ready(function () {

            // Initialize materialize data picker
            $('.datepicker').datepicker({ 'format': 'yyyy-mm-dd' });
            $('select').formSelect();

        });
    </script>

    <script src="{% static 'app/dist/js/materialize.js' %}"></script>

    <script src="{% static 'app/dist/js/materialize.min.js' %}"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- INICIALIZACION MODAL -->
    <script>document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.modal');
            var instances = M.Modal.init(elems);
        });</script>

    <script>
        $(".dropdown-trigger").dropdown();
    </script>

</body>

</html>

app/templates/app/modificar_producto.html
{% extends 'app/base.html' %}
{% load static %}
{% load materializecss %}
{% block contenido %}

<br><br><br><br><br><br>
<div class="row">
    <div class="col l2"></div>
    <div class="col l8">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form }}
            </table>
            <br><br>
            <input onclick="confirmarModificar()" type="submit" class="btn" value="Modificar"> 
            <input type="reset" class="btn" value="Limpiar">
            <br><br><br><br><br><br><br>
        </form>
        {{ mensaje }}
    </div>
    <div class="col l2"></div>
</div>

{% endblock %}

{% block javascript %}

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'app/dist/js/funcionalidades.js' %}"></script>

{% endblock %}

app/templates/offline.html
{% extends 'app/base.html' %}

{% block contenido %}

<br><br><br>

<div class="row container">
    <div class="row">
        <h1>Estimado cliente, usted no tiene Internet</h1>
    </div>
</div>

{% endblock %}